version: '3.8'

services:
  backend:
    build:
      context: ./candidate-api
      dockerfile: Dockerfile
    container_name: candidate-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./candidate-frontend
      dockerfile: Dockerfile
    container_name: candidate-frontend
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
